### ISSUE TITLE
More features faster blockers

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#1240]
We have a lot of experience creating features now, having covered ~18% of BCD keys with web-features. We've learned a lot about what tends to take a long time when defining and reviewing features, and have a bunch of ideas to increase velocity.

These are the issues that need to be resolved to move faster:

- [x] https://github.com/web-platform-dx/web-features/pull/1204
- [x] https://github.com/web-platform-dx/web-features/pull/1231
- [x] https://github.com/web-platform-dx/web-features/pull/1227
- [x] https://github.com/web-platform-dx/web-features/issues/1211
- [x] https://github.com/web-platform-dx/web-features/issues/938

With these done, we can then fully focus on the "more features" part and cover ~100% of BCD.

Discussed today with @ddbeck and @Elchi3.

**Comment by foolip** [comment]
@ddbeck have I missed anything important? Here are the things I considered and did not list:

- https://github.com/web-platform-dx/web-features/pull/1208, but we need _something_ to improve velocity for very old features
- https://github.com/web-platform-dx/web-features/issues/1018 might be that something
- https://github.com/web-platform-dx/web-features/pull/1060
- https://github.com/web-platform-dx/web-features/issues/1173
- https://github.com/web-platform-dx/web-features/issues/1038
- https://github.com/web-platform-dx/web-features/issues/971
- https://github.com/web-platform-dx/web-features/issues/915
- https://github.com/web-platform-dx/web-features/issues/623

**Comment by ddbeck** [comment]
Yes, I think the issues you mentioned in the issue description are the true blockers and the others aren't blockers _yet_.

For completeness, I thought of a couple more things that would speed us up (but are also not yet blocking) that don't think have issues yet, for synchronization between web-features and BCD:

- Automatically opening PRs to create new draft features in web-features from new tags in BCD
- Automatically opening PRs to migrate `compat_features` to BCD tags

**Comment by Elchi3** [comment]
> * Automatically opening PRs to create new draft features in web-features from new tags in BCD
> * Automatically opening PRs to migrate `compat_features` to BCD tags

+1. Very interested in these two.
