### ISSUE TITLE
Burndown processing: 2023-2024 features

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/web-features#863]
@foolip and I reviewed the [_Baseline 2023+ candidates_](https://docs.google.com/spreadsheets/d/1RVgaq4ruHYeJvLCky-h2VAreRP5j_CKifaBvwYEhsL0/edit#gid=1279455993&fvid=922381154) burndown list today.

What follows is compat keys (or hints about which keys to search the burndown list for), but there's probably more unpacking/investigation to be done.

A list of potential features came out of that:

## Potentially new (~2023-2024)

- [x] `inert` attribute (https://github.com/web-platform-dx/web-features/pull/909)
- [x] `*RenderingContext2D.{createConicGradient,getContextAttributes,reset,roundRect}` ([see also](https://developer.chrome.com/blog/canvas2d)) (https://github.com/web-platform-dx/web-features/pull/1064)
- [x] `messageerror` (https://github.com/web-platform-dx/web-features/pull/911)
- [x] `PushNotification` (https://github.com/web-platform-dx/web-features/pull/912)
- [x] `ScreenOrientation` (https://github.com/web-platform-dx/web-features/pull/913)
- [x] `Navigator.userActivation` (https://github.com/web-platform-dx/web-features/pull/887)
- [x] `counter-set` CSS property (https://github.com/web-platform-dx/web-features/pull/914)
- [x] `api.*.ecmascript_modules` (https://github.com/web-platform-dx/web-features/pull/1012)
- [x] Abortable things (`api.{NavigateEvent,Request,WritableStreamDefaultController}.signal` (https://github.com/web-platform-dx/web-features/pull/989, https://github.com/web-platform-dx/web-features/pull/990)
- [x] `hyphens` property (unprefixed) (https://github.com/web-platform-dx/web-features/pull/916)
- [x] `image-set()` CSS function (https://github.com/web-platform-dx/web-features/pull/928)
- [ ] `offset-path` (add to existing feature, probably things like `ray`)
- [x] ~~`Clear-Site-Data` header~~ (dropped, see https://github.com/web-platform-dx/web-features/issues/863#issuecomment-2067757266)
- [x] `Sec-Fetch-*` (https://github.com/web-platform-dx/web-features/pull/991)
- [x] [`ArrayBuffer.prototype.transfer` and friends](https://github.com/tc39/proposal-arraybuffer-transfer) (https://github.com/web-platform-dx/web-features/pull/987)
- [x] WebAssembly SIMD (https://github.com/web-platform-dx/web-features/pull/931)
- [x] Submittable [`dirname`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/dirname#browser_compatibility) (https://github.com/web-platform-dx/web-features/pull/995)
- [x] `ElementInternals` (https://github.com/web-platform-dx/web-features/pull/1003)
- [x] `navigator.mediaDevices.enumerateDevices()` (https://github.com/web-platform-dx/web-features/pull/929)
- [x] Origin private file system (https://github.com/web-platform-dx/web-features/pull/1033)
- [x] `TextMetrics` `alphabeticBaseline` (https://github.com/web-platform-dx/web-features/pull/884)
- [x] `URL` `canParse()` (https://github.com/web-platform-dx/web-features/pull/996)
- [x] `window.print()` (https://github.com/web-platform-dx/web-features/pull/1039)
- [x] CSS `display` multi-keyword (https://github.com/web-platform-dx/web-features/pull/1036)
- [x] `font-synthesis-weight` (https://github.com/web-platform-dx/web-features/pull/970)
- [x] Unprefixed `mask-clip` (https://github.com/web-platform-dx/web-features/pull/1037)
- [ ] Media queries in `<source>`

## Potentially older

- [ ] `DOMMatrix` and other geometry stuff (2020ish?) 
- [ ] Responsive images (`sizes`, `srcset`, `<picture>`)
- [ ] `Notification` (initial support)
- [ ] `PerformanceResourceTiming`
- [ ] Root font units (`rem`, `rlh`, etc.)

**Comment by foolip** [comment]
There are multiple ways we could handle `api.*.ecmascript_modules`. We could treat it as part of the "living" JS modules feature/group. Or we could add a "Worker modules" representing support for what's described in https://web.dev/articles/module-workers#enter_module_workers, which in the long term we consider part of modules more broadly.

**Comment by foolip** [comment]
For `Clear-Site-Data`, [the compat table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data#browser_compatibility) suggests that there is actually no interoperable subset that can be used in all browsers, except `Clear-Site-Data: "*"` which would do different things in different browsers, with no overlapping behavior.

**Comment by ddbeck** [comment]
> If we want a feature for worker modules, then [mdn/browser-compat-data#22884](https://github.com/mdn/browser-compat-data/pull/22884) needs to land first.

That sounds like a feature to me. I reviewed, approved, and merged the BCD PR.

**Comment by foolip** [comment]
`navigator.mediaDevices.enumerateDevices()` isn't a Baseline 2023 feature, but I've sent https://github.com/web-platform-dx/web-features/pull/929 with what I think the feature should be.

**Comment by foolip** [comment]
OPFS is the entry point defined in https://fs.spec.whatwg.org/#sandboxed-filesystem.

**Comment by foolip** [comment]
CSS `display` multi-keyword is "css.properties.display.multi-keyword_values" in BCD, but I'm not totally sure it's notable enough to be its own feature. It's a new part of `display` for sure, but I'm not sure what to call a feature for it.

**Comment by ddbeck** [comment]
> CSS `display` multi-keyword is "css.properties.display.multi-keyword_values" in BCD, but I'm not totally sure it's notable enough to be its own feature. It's a new part of `display` for sure, but I'm not sure what to call a feature for it.

I _very_ nearly came down the same way on this before backtracking. 😅 See https://github.com/web-platform-dx/web-features/pull/1036 for all the details.

**Comment by ddbeck** [comment]
I think this is now satisfied, or will be shortly by our wide-ranging coverage work in progress. Closing this up.
