### ISSUE TITLE
Authorize `compute-baseline` to grant Baseline statuses to single keys in `@mdn/browser-compat-data`

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/web-features#979]
Also known as "blessing" single-compat keys' status from compute-baseline.

## Background

Through a combination of governance documentation, Baseline definition, and convention, explicit review and publication is required for a status to be assigned to a web platform feature. This issue proposes that we authorize—under a specific combination of code and data—certain BCD keys to receive statuses without explicit review.

## Motivation

Typically, we expect consumers of Baseline data to show a status for a feature as a whole, taken directly from the `web-features` package. For example, if you go to [the Popover API overview page on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API), then you ought to see a status relating to whole popover feature.

However, this doesn't make sense in every context. If you go to the MDN reference page for a specific popover property or method, then MDN ought to be able to show a Baseline status that reflects that _specific_ property or method's status.

## Proposal

Permit official Baseline statuses to be generated from standalone BCD keys, using an approved method in the `compute-baseline` package.

Some additional limitations:

- Only keys that are part of a feature, group, or snapshot of `web-features` are eligible for a status. Arbitrary, uncategorized keys will not be eligible for computation (e.g., since they might be still under editorial review). This ensures that the underlying data will receive some scrutiny before setting a status.
- Statuses should only be generated from the current or previous releases of `compute-baseline`, `web-features`, and `@mdn/browser-compata-data`. Consumers using this approach should take care to avoid stale statuses.

## Tasks

If adopted, we'd need to do the following:

- [ ] Make required changes to `compute-baseline`: create an authorized single-key method that returns a plain JS object like the data found in the `status` block of `web-features` data
- [ ] Document `web-features` and `compute-baseline` as the only official sources of Baseline status data

Optionally we might:

- [ ] Provide pre-computed JSON for non-JS consumers who need this data
- [ ] Consider synchronizing `compute-baseline`'s version number with `web-features` (from 1.0)

**Comment by foolip** [comment]
> This issue proposes that we authorize—under a specific combination of code and data—certain BCD keys to receive statuses without explicit review.

Would we not consider it reviewed via the feature? With dist files in the style of https://github.com/web-platform-dx/web-features/issues/866#issuecomment-2078907927, the status of each individual BCD key would be checked in and reviewed.

**Comment by foolip** [comment]
From https://github.com/web-platform-dx/web-features/issues/1164 it is clear that we need to think about the case where one BCD key is part of multiple features.

Should we require consumers to ask about a BCD key in the context of a feature? If a BCD key has a different Baseline status in different contexts, what should be shown in an MDN page which is about only that BCD key?

Or should we disallow assigning one BCD key to multiple features?

**Comment by foolip** [comment]
This is now done.
